[theme]
base="light"

primaryColor="#1F5AA6"

backgroundColor="#FFFFFF"

secondaryBackgroundColor="#F3F6FB"

textColor="#111827"

font="sans serif"

[server]
headless=true

[browser]
gatherUsageStats=false